### ISSUE TITLE
App does not handle when integration is unable to communicate with car.

### ISSUE THREAD

**Issue by tobbensoft** [EvTheFuture/SmartCharging#9]
For some reason car couldn't be woken when charging should begin.

The app reports charging but it never succeed with the command to the car.

Not sure if you can get any status back, or we just need to check it.

![image](https://user-images.githubusercontent.com/46381052/101267137-f3628500-3755-11eb-95f7-383a3e1f9d9a.png)
![image](https://user-images.githubusercontent.com/46381052/101267155-1725cb00-3756-11eb-9b16-9a4edc717103.png)
![image](https://user-images.githubusercontent.com/46381052/101267146-04ab9180-3756-11eb-84b0-d70515ae3524.png)

```2020-12-05 23:03:27 INFO (MainThread) [teslajsonpy.controller] Backing off command(...) for 11.2s (teslajsonpy.exceptions.RetryLimitError)
2020-12-05 23:07:06 ERROR (MainThread) [teslajsonpy.controller] Giving up command(...) after 2 tries (teslajsonpy.exceptions.RetryLimitError)
2020-12-05 23:07:06 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall switch.turn_on (c:f9f491efe28a1a25ea075c8d871a89a1): entity_id=['switch.old_grey_charger_switch']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1461, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 593, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 630, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/tesla/switch.py", line 32, in async_turn_on
    await self.tesla_device.start_charge()
  File "/usr/local/lib/python3.8/site-packages/teslajsonpy/homeassistant/charger.py", line 64, in start_charge
    data = await self._controller.command(
  File "/usr/local/lib/python3.8/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/teslajsonpy/controller.py", line 476, in command
    return await self.post(
  File "/usr/local/lib/python3.8/site-packages/teslajsonpy/controller.py", line 174, in wake_up
    raise RetryLimitError("Reached retry limit; aborting wake up")
teslajsonpy.exceptions.RetryLimitError
2020-12-05 23:53:36 INFO (MainThread) [teslajsonpy.controller] Backing off command(...) for 12.7s (teslajsonpy.exceptions.RetryLimitError

**Comment by EvTheFuture** [comment]
Yes, the app does currently not validate that it actually was able to start the charging. This can be improved.
